docs/crd_mysql_backup.md, docs/crd_mysql_backup_schedule.md, docs/crd_mysql_cluster.md, docs/design.md
- Add retentionPeriodDays to MySQLBackup
- Fix some trivial things
Signed-off-by: dulltz <isrgnoe@gmail.com>
=> docs: Fix design

docs/design.md
=> Add recovery from blackouts scenario to design doc.

Makefile
Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>
=> Fix build target

e2e/Makefile
=> Remove delete operations from e2e test Makefile.

constants.go, controllers/mysql_conf.go, e2e/manifests/moco-controller.yaml
Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>
=> Use latest moco-conf-gen

.gitignore, Makefile, accessor/infrastructure.go, accessor/mysql_accessor.go, accessor/mysql_status.go, accessor/mysql_status_test.go, accessor/suite_test.go, cmd/moco-controller/cmd/run.go, config/default/manager_auth_proxy_patch.yaml, config/rbac/role.yaml, constants.go, controllers/mysql_clustering.go, controllers/mysql_clustering_test.go, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, controllers/suite_test.go, e2e/Makefile, go.mod
This PR implements the feature to update a controller to reconcile services for primary and replica MySQL pods.
=> Update controller to create Service resources

agent/agent.go, agent/clone.go, agent/rotate.go, api/v1alpha1/mysqlcluster_types.go, cmd/entrypoint/cmd/agent.go, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, constants.go, controllers/mysql_clustering.go, controllers/mysqlcluster_controller.go, deploy/crd.yaml, e2e/.gitignore, go.mod
This PR adds the token auth mechanism for agent sidecar's APIs.
=> Add token for agent call

controllers/mysql_clustering.go, controllers/mysql_clustering_test.go, operators/clone.go, operators/configure_replication.go, operators/operator.go, operators/set_clone_donor_list.go, operators/set_labels.go, operators/turn_off_read_only.go, operators/update_primary.go
=> Move Operators to operators package

.circleci/config.yml, Makefile, accessor/mysql_status_test.go, agent/agent.go, agent/clone.go, agent/clone_test.go, agent/health.go, agent/health_test.go, agent/rotate.go, agent/rotate_test.go, agent/suite_test.go, cmd/entrypoint/cmd/agent.go, my.cnf
=> Add tests for agent sidecar

controllers/mysql_clustering_test.go
=> Refactor controller's tests.

.github/workflows/ci.yaml, .github/workflows/release.yaml, Dockerfile, Makefile, e2e/Makefile, e2e/kind-cluster.yaml
=> Move to Actions

.gitignore
=> ignore `tmp` dir created temporarily by make kubebuilder

accessor/mysql_status_test.go
=> Tests for GetLatestInstance.

accessor/mysql_status.go
=> use column alias name for expression query

cmd/moco-controller/cmd/run.go, config/rbac/role.yaml, constants.go, controllers/mysql_clustering.go, controllers/mysql_clustering_test.go, controllers/mysqlcluster_controller.go, docs/events.md, e2e/README.md
This PR adds k8s `Event` recording while reconciliations.
=> Add Event recording.

controllers/mysqlcluster_controller.go
=> Fix init Event record.

agent/suite_test.go, constants.go, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/crd_mysql_cluster.md, operators/suite_test.go
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
=> Add tests for reconcileInitialize

docs/design.md
=> fix broken list in document.

accessor/mysql_status.go, agent/clone.go, agent/clone_test.go, agent/health_test.go, agent/rotate_test.go, agent/suite_test.go, agent/test_data/CLONE_PASSWORD, agent/test_data/CLONE_USER, constants.go, controllers/mysql_clustering.go, controllers/mysql_clustering_test.go, e2e/intermediate_primary_test.go, e2e/manifests/mysql_cluster_external.yaml, e2e/primary_failover_test.go, e2e/run_test.go, e2e/suite_test.go, initialize/init.go, initialize/init_test.go, operators/configure_intermediate_primary.go, operators/configure_intermediate_primary_test.go
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
=> Add e2e tests for intermediate primary

agent/clone.go, constants.go, e2e/intermediate_primary_test.go, initialize/init.go, initialize/init_test.go, test_utils.go
=> Not delete all users before initializing

accessor/mysql_status.go
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
=> Fix connection leak

constants.go, controllers/mysqlcluster_controller.go, initialize/init.go, initialize/init_test.go
=> add moco-readonly and moco-writable users.

controllers/mysqlcluster_controller.go
=> fix setLabels function and use it from makePodTemplate too.

.github/workflows/ci.yaml, controllers/mysql_clustering.go, controllers/mysql_clustering_test.go, controllers/mysqlcluster_controller.go, e2e/bootstrap_test.go, e2e/intermediate_primary_test.go, e2e/kubectl_moco_test.go, e2e/primary_failover_test.go, e2e/replica_failover_test.go, e2e/run_test.go, e2e/suite_test.go
=> Fix to stabilize CI.

config/manager/manager.yaml, e2e/manifests/kustomization.yaml
=> fix deployment manifest

.github/workflows/ci.yaml, e2e/Makefile, e2e/kind-cluster-actions.yaml
=> Use /mnt for MySQL data on GitHub Actions

controllers/mysql_clustering.go, controllers/mysql_clustering_test.go, operators/constants.go, operators/set_labels.go, operators/set_labels_test.go
=> rename setLabels op to setRoleLabels

cmd/kubectl-moco/cmd/root.go, go.mod
Signed-off-by: zoetrope <a.ikezoe@gmail.com>
=> kubectl-moco: add klog options

api/v1alpha1/mysqlcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/crd_mysql_cluster.md
=> Add secrityContext for log rotation job.

config/kustomization.yaml, config/manager/manager.yaml, config/namespace.yaml
=> manifest: Add prefix to cluster-wide objects.

cmd/kubectl-moco/cmd/mysql.go, constants.go, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go
=> Use --defaults-extra-file to exec mysql command

config/manager/manager.yaml
=> Fix resource requests/limits.

config/rbac/kustomization.yaml, config/rbac/mysqlcluster_editor_role.yaml, config/rbac/mysqlcluster_viewer_role.yaml
=> manifest: publish editor/viewer ClusterRoles with aggregation labels.

cmd/kubectl-moco/cmd/credential.go, cmd/kubectl-moco/cmd/mysql.go, docs/kubectl-moco.md
=> kubectl-moco: Change --user option name

cmd/entrypoint/cmd/init.go
=> Fix not to override err.

docs/build-mysql.md, ping.sh
=> Add document about how to build MySQL container image.

docs/example_mysql_cluster.md
=> docs: Add example of MySQLCluster CR.

agent/clone.go, agent/rotate.go
=> Enhance the validation of agent request

agent/clone.go, agent/health.go, agent/rotate.go
=> Fix improper variables references

controllers/mysql_conf.go, controllers/mysql_conf_test.go, controllers/mysqlcluster_controller.go
=> Remove unused option of mysqlConfGenerator

agent/clone.go
Add a comment for the following behavior after cloning.
https://dev.mysql.com/doc/refman/8.0/en/clone-plugin-remote.html
>By default, the recipient MySQL server instance is restarted (stopped and started) automatically after the data is cloned. For an automatic restart to occur, a monitoring process must be available on the recipient to detect server shutdowns. Otherwise, the cloning operation halts with the following error after the data is cloned, and the recipient MySQL server instance is shut down:
>> ERROR 3707 (HY000): Restart server failed (mysqld is not managed by supervisor process).
=> Add comment for error check after cloning

agent/clone.go, agent/health.go, agent/rotate.go
ref: https://github.com/cybozu-go/moco/issues/127
=> Make agent log message identifiable

.github/workflows/ci.yaml, e2e/Dockerfile, e2e/Makefile
ref: https://github.com/cybozu-go/moco/issues/121
Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>
=> Run e2e test for MySQL 8.0.18, 20

README.md
=> Update supported MySQL versions

.github/workflows/ci.yaml, e2e/Makefile, e2e/script/show_container_log.sh, e2e/script/watch_mysql.sh, e2e/script/watch_pod.sh
I want to use CI to check:
- the status of MySQL instances and pods
- system variables of MySQL instances
=> Watch MySQL and Pods on CI

controllers/mysql_clustering.go
The reconciliation is being performed twice at once.
moco-controller updates the status of MySQLCluster CR at the end of reconciliation.
And after this status update, the second reconciliation will be started immediately.
In a steady-state, even if the status does not need to be changed, the update is executed. And it causes meaningless reconciliation.
To prevent this meaningless reconciliation, update status only when there are changes.
This behavior can be seen in the moco-controller's log.
```
2021-01-13T11:50:41.820Z        DEBUG   controller      Successfully Reconciled {"reconcilerGroup": "moco.cybozu.com", "reconcilerKind": "MySQLCluster", "controller": "mysqlcluster", "name": "mysqlcluster", "namespace": "e2e-test-external"}
2021-01-13T11:50:41.825Z        DEBUG   controller …
```
=> Update the status only when there are changes

controllers/mysqlcluster_controller_test.go, controllers/suite_test.go
Change the controllers test as follows.
- Simplify the accessor mock.
This test does not seem to access a MySQL server. The parameters in the mock are confusing.
- Change the variable name. (`namespace` -> `clusterNamespace`)
=> Fix controller test

Makefile, initialize/Dockerfile
=> Make MySQL version configurable in initialize test

.github/workflows/ci.yaml, Makefile, accessor/suite_test.go, agent/suite_test.go, test_utils/test_utils.go
Some minor changes.
- Change test password 
- Remove unnecessary make target `start-mysqld` and `stop-mysqld`
- Suppress mysql client log in accessor test
- Remove redundant setting in agent test
=> Change test password and remove unused make target

.github/workflows/ci.yaml, Makefile, README.md, common.mk, config/rbac/leader_election_role.yaml, config/rbac/role.yaml, controllers/mysqlcluster_controller.go, e2e/Makefile, e2e/gc_test.go, e2e/kind-cluster-actions.yaml, e2e/kind-cluster.yaml, go.mod
=> test: Add k8s matrix e2e test.

agent/clone_test.go, e2e/intermediate_primary_test.go, operators/suite_test.go
=> Enable the spec of unit test in clone_test.go

Makefile
=> Build all commands in make default rule

.github/workflows/release.yaml
=> Add kubectl-moco release workflow for windows.

controllers/mysqlcluster_controller.go
=> Suppress error log after deletion of MySQLCluster

.github/workflows/ci.yaml, RELEASE.md
=> Change default branch name: master -> main

e2e/suite_test.go
=> e2e test bootstrap

CHANGELOG.md, RELEASE.md, go.mod
=> Bump version to 0.5.0

e2e/Makefile
=> Download e2e test tools for the host OS

CHANGELOG.md
=> Bump version to 0.5.1

controllers/mysqlcluster_controller.go, docs/design.md, e2e/gc_test.go, e2e/suite_test.go
https://github.com/cybozu-go/moco/issues/188
=> PVC auto deletion

cmd/moco-controller/cmd/root.go
=> moco-agent v0.2.1

controllers/mysqlcluster_controller_test.go, docs/build-mysql.md, docs/example_mysql_cluster.md
https://github.com/cybozu-go/moco/issues/191
=> remove ping.sh from documents and test

cmd/moco-controller/cmd/root.go, cmd/moco-controller/cmd/run.go, controllers/mysqlcluster_controller.go, controllers/suite_test.go, docs/moco-controller.md
refs: https://github.com/cybozu-go/moco/pull/198#discussion_r581640715
Delete the unused variables that I forgot to delete in #173
=> Remove unused curl container image variables.

controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/example_mysql_cluster.md, e2e/manifests/mysql_cluster.yaml, e2e/manifests/mysql_cluster_external.yaml
https://github.com/cybozu-go/moco/issues/197
=> set liveness and readiness probes automatically

docs/setup.md
Add setup document as I could not find any :)
=> Add Setup Document

accessor/suite_test.go, e2e/Makefile, e2e/intermediate_primary_test.go
=> test: extend timeout for setup.

.github/workflows/mdbook.yaml, CHANGELOG.md, Makefile, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, kustomization.yaml, version.go
The old way caused a trobule with Argo CD.
Also, this commit prepares for v0.9.1.
=> Change the way to shrink MySQLCluster CRD

CHANGELOG.md, Makefile, clustering/manager.go, cmd/moco-controller/cmd/run.go, controllers/mock_test.go, controllers/mysqlcluster_controller_test.go, controllers/pod_watcher.go, controllers/pod_watcher_test.go, kustomization.yaml, version.go
to make automatic switchover happen immediately.
=> Watch Pod deletion and notify the cluster manager

config/manager/manager.yaml, config/rbac/kustomization.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml
=> Create Service Account for moco controller

controllers/mysqlcluster_controller.go
Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>
=> Fix restore job fails to create an event

controllers/mysqlcluster_controller_test.go
=> Prevent sts from being updated accidentally

.github/workflows/ci.yaml, DEVELOP.md, Dockerfile, Makefile, README.md, docs/custom-mysqld.md, docs/usage.md, e2e/Makefile, examples/anti-affinity.yaml, examples/collect-metrics.yaml, examples/custom-mycnf.yaml, examples/guaranteed.yaml, examples/loadbalancer.yaml
refs: https://github.com/cybozu-go/moco/issues/285
=> Add MySQL 8.0.26 Support

README.md, api/v1beta1/mysqlcluster_types.go, api/v1beta1/mysqlcluster_webhook_test.go, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, docs/clustering.md, docs/crd_mysqlcluster.md
refs: https://github.com/cybozu-go/moco/issues/286
=> Supports more than 5 MySQL instances

RELEASE.md, charts/moco/README.md, charts/moco/values.yaml
=> Add release procedure for Helm Chart

docs/install-plugin.md
=> Fix to use curly brackets

.krew.yaml
Reflect the description corrected by Pull Request of krew-index:
https://github.com/kubernetes-sigs/krew-index/pull/1721#issuecomment-960386481
=> Update krew description

cmd/kubectl-moco/cmd/root.go, cmd/moco-controller/cmd/root.go, go.mod, go.sum
=> Use klog v2

Makefile
=> Don't install mysql packages

version.go
=> Update Fluent Bit container image

clustering/status.go, pkg/dbop/nop.go, pkg/dbop/operator.go
=> Do not stop gathering cluster status if one or more Pods are pending

clustering/status.go
=> Add nil check

controllers/mysqlcluster_controller.go
When creating volumeClaimTemplates, if the owner's MySQLCluster is already specified as v1beta1, updating apiVersion will cause apply to fail.
> failed to reconcile stateful set: StatefulSet.apps \"moco-test\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
This PullRequest will fix the apiVersion of the PVC owner reference specified in the volumeClaimTemplates of the StatefulSet that has already been created in the cluster so that it does not change.
error log:
```
{"level":"error","ts":1645353149.3845217,"logger":"controller.mysqlcluster","msg":"Reconciler error","reconciler group":"moco.cybozu.com","reconciler kind":"MySQLCluster","name":"test","namespace":"default","error":"failed
to reconcile …
```
=> Fixed StatefulSet apply failures.

controllers/mysqlcluster_controller.go
refs: https://github.com/cybozu-go/moco/issues/306
Create Secret using server-side-apply
=> Using SSA to create Secret

docs/designdoc/allow_customize_containers.md
refs: https://github.com/cybozu-go/moco/issues/235
=> Add design doc for allow users to customize containers

docs/SUMMARY.md, docs/known_issues.md
This PR adds description about the known issue https://github.com/cybozu-go/moco/issues/322.
This description should be removed when the issue is fixed.
=> Clarify a known issue about multi-threaded replication

docs/known_issues.md
=> Fix link format in doc

version.go
=> Update mysqld_exporter and Fluent Bit

.github/workflows/release.yaml
=> CI/CD: disable latest image tag

controllers/mysqlcluster_controller.go, controllers/pvc.go, e2e/mycluster.yaml, e2e/pvc_test.go, e2e/testdata/pvc_test.yaml, e2e/testdata/pvc_test_changed.yaml
refs: https://github.com/cybozu-go/moco/issues/265
depends: https://github.com/cybozu-go/moco/pull/403
Implement e2e test for pvc template changes and pvc resize functionality.
=> Added e2e test to change pvc template

docs/SUMMARY.md, docs/change-pvc-template.md, docs/metrics.md, e2e/class.yaml, e2e/class2.yaml, e2e/m.yaml
refs: #265
Add user docs for pvc template changes.
=> Added docs on modifying pvc templates.

pkg/mycnf/generator.go, pkg/mycnf/testdata/bufsize.cnf, pkg/mycnf/testdata/loose.cnf, pkg/mycnf/testdata/nil.cnf, pkg/mycnf/testdata/normalize.cnf, pkg/mycnf/testdata/opaque.cnf
https://github.com/cybozu-go/moco/issues/445
=> issue-445: Remove max_connect_errors setting as it is meaningless

version.go
=> update fluent-bit and mysqld_exporter container

controllers/mysqlcluster_controller.go
fix https://github.com/cybozu-go/moco/issues/449
Signed-off-by: yamatcha <soju-yamashita@cybozu.co.jp>
=> Detect differences of service appropriately

pkg/dbop/kill.go
fixed https://github.com/cybozu-go/moco/issues/475
=> Ignore MySQL error 1094 when killing connections

.github/workflows/ci-e2e.yaml, .github/workflows/helm-release.yaml, .github/workflows/helm.yaml, .github/workflows/weekly.yaml, Dockerfile, README.md, e2e/Makefile
=> Support MySQL 8.0.31

Dockerfile, e2e/backup_test.go
fixed https://github.com/cybozu-go/moco/issues/486
=> Donwgrade mysqlsh to 8.0.30

cmd/moco-controller/cmd/root.go, cmd/moco-controller/cmd/run.go, controllers/mysqlcluster_controller.go, controllers/pod_watcher.go, docs/moco-controller.md
=> Add max-concurrent-reconciles option

.github/workflows/ci-e2e.yaml, .github/workflows/ci.yaml, .github/workflows/dbtest.yaml, .github/workflows/e2e.yaml, .github/workflows/weekly.yaml
refs: https://github.com/actions/setup-go/releases/tag/v3.2.0
=> Enable go.mod cache

.github/workflows/release.yaml, Dockerfile
=> Build moco-controller with go 1.19

.github/workflows/ci-e2e.yaml, .github/workflows/weekly.yaml, Dockerfile, README.md, e2e/Makefile
=> Support MySQL 8.0.32

.github/workflows/release.yaml, Dockerfile, e2e/Makefile, go.mod, go.sum, version.go
- https://github.com/cybozu-go/moco/issues/490
- https://github.com/cybozu-go/moco-agent/pull/79
=> Support multi-platform

cmd/moco-controller/cmd/root.go, cmd/moco-controller/cmd/run.go, docs/moco-controller.md
=> Add qps flag

api/v1beta2/mysqlcluster_types.go, api/v1beta2/mysqlcluster_webhook_test.go, controllers/pvc.go, controllers/pvc_test.go, docs/change-pvc-template.md, e2e/pvc_test.go, e2e/run_test.go, e2e/testdata/pvc_test.yaml, e2e/testdata/pvc_test_changed.yaml
https://github.com/cybozu-go/moco/issues/537
Support redunce volume size in MOCO.
It is implemented based on the proposals added below.
* https://github.com/cybozu-go/moco/pull/538
=> Support redunce volume size

Dockerfile, docs/change-pvc-template.md
=> Fix image name and tag

Dockerfile, go.mod, go.sum
=> Build moco-controller with go 1.21

docs/backup.md
`` is "Markdown All in One" tag.
I'm not sure that other document files such as clustering.md and usage.md. (Several very low-level sections do not appear in ToC in clustering.md)
=> update ToC in backup.md

pkg/dbop/kill_test.go
Reverts cybozu-go/moco#515
This fix is buggy.
https://github.com/cybozu-go/moco/pull/580#issuecomment-1780229611
=> Revert "Fix flaky test"

.github/workflows/release.yaml
=> Bump goreleaser-action and goreleaser

api/v1beta1/backuppolicy_types.go, api/v1beta1/mysqlcluster_types.go, charts/moco/templates/generated/crds/moco_crds.yaml, config/crd/bases/moco.cybozu.com_backuppolicies.yaml, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_backuppolicies.moco.cybozu.com.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_mysqlclusters.moco.cybozu.com.yaml, e2e/testdata/backup.yaml, e2e/testdata/backup_gcs.yaml, e2e/testdata/backup_tls.yaml
Part of https://github.com/cybozu-go/moco/issues/545
=> api: add unservedversion marker

backup/backup.go
=> fix wrong error message

.github/workflows/build-fluent-bit-container.yaml, .github/workflows/build-mysql-container.yaml, .github/workflows/build-mysqld-exporter-container.yaml, .github/workflows/ci-e2e.yaml, .github/workflows/ci.yaml, .github/workflows/dbtest.yaml, .github/workflows/e2e.yaml, .github/workflows/helm-release.yaml, .github/workflows/helm.yaml, .github/workflows/mdbook.yaml, .github/workflows/release.yaml, .github/workflows/weekly.yaml
Update actions and allows build-containers workflow to run when new tag is not added.
=> Upgrade actions in CI

containers/fluent-bit/Dockerfile, containers/mysql/8.0.18/Dockerfile, containers/mysql/8.0.25/Dockerfile, containers/mysql/8.0.26/Dockerfile, containers/mysql/8.0.27/Dockerfile, containers/mysql/8.0.28/Dockerfile, containers/mysql/8.0.30/Dockerfile, containers/mysql/8.0.31/Dockerfile, containers/mysql/8.0.32/Dockerfile, containers/mysql/8.0.33/Dockerfile, containers/mysql/8.0.34/Dockerfile, containers/mysql/8.0.35/Dockerfile, containers/mysqld_exporter/Dockerfile
Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>
=> Migrate to ghcr.io

backup/key.go, pkg/bucket/gcs_test.go, pkg/bucket/interface.go, pkg/bucket/s3_test.go
=> Add / delimiter to the end of path in calcPrefix

.github/workflows/ci-e2e.yaml
=> Fix changed-files args

controllers/mysqlcluster_controller.go
=> Add mysql-admin port to the headless service

charts/moco/README.md, charts/moco/templates/deployment.yaml, charts/moco/values.yaml
Hi,
This will allow setting a custom PriorityClass for the controller, so that it run with a higher than normal priority and better resist to outages and busy clusters.
Cheers
=> chart: add value to set a PriorityClass

version.go
Update version.go for fluent-bit & mysql_exporter
=> Update version.go for new image

pkg/mycnf/generator.go, pkg/mycnf/generator_test.go
refs: https://github.com/cybozu-go/moco/issues/638
=> Prevent disabling of binlog

api/v1beta2/mysqlcluster_webhook.go, api/v1beta2/mysqlcluster_webhook_test.go
refs: https://github.com/cybozu-go/moco/issues/502
=> Limit cluster name length

pkg/dbop/kill.go
https://github.com/cybozu-go/moco/issues/710
=> issue-710: Do not kill system user

controllers/partition_controller.go, controllers/partition_controller_test.go
This PR fixes https://github.com/cybozu-go/moco/issues/779.
I modified predicate functions and filtered out the target of the StatefulSetPartitionReconciler.
=> Narrow down the target of StatefulSetPartitionReconciler

docs/SUMMARY.md
=> docs: fix spelling in summary.md

clustering/operations.go
=> issue-797: Improved log messages when replication is stopped due to errant_replica

charts/moco/README.md, charts/moco/templates/podmonitor.yaml, charts/moco/values.yaml
=> Prometheus PodMonitors configured by Helm chart

clustering/mock_test.go, clustering/status.go, clustering/status_test.go, docs/clustering.md, pkg/dbop/status.go, pkg/dbop/status_test.go, pkg/dbop/types.go
=> exclude replicas with uncommitted trx during failover

Makefile, api/v1beta2/webhook_suite_test.go, aqua.yaml, backup/suite_test.go, clustering/suite_test.go, controllers/suite_test.go
=> download assets without setup-envtest
