controllers/mysql_conf.go
Mysqlbinlog emits an error and aborts if default_caracter_set is specified because it doesn't interpret it. Adding the loose prefix to default_character_set has mysqlbinlog ignore it, it emits a warning though.
```
$ mysqlbinlog -v /var/lib/mysql/binlog.000002
mysqlbinlog: [ERROR] unknown variable 'default_character_set=utf8mb4'.
```
=> Add loose to default_character_set

controllers/mysql_conf.go
- innodb_validate_tablespace_paths
OFF by default to improve the startup time in environments
having a lot of tables.
- temptable_use_mmap
Move from const to default because this is fixed in 8.0.21.
- relay_log_recovery
OFF to avoid the risk of transaction loss.
=> conf: misc updates

cmd/kubectl-moco/cmd/common.go, cmd/kubectl-moco/cmd/credential.go, cmd/kubectl-moco/cmd/mysql.go, cmd/kubectl-moco/cmd/root.go
This PR fixes `kubectl-moco` to use the existing `kubectl exec` implements because it has more detailed error handling.
=> Fix kubectl moco to enable interactive exec.

cmd/kubectl-moco/cmd/common.go, cmd/kubectl-moco/cmd/credential.go, cmd/kubectl-moco/cmd/mysql.go
- Stop using global variables that depend on `mysql` subcommands in common functions.
- Fix usage of the `credential` subcommand.
=> Minor fix of kubectl-moco

cmd/moco-controller/cmd/run.go
MOCO does not implement webhook, so the `ctrl.Options.Port` option is not necessary.
=> Delete unused port definition

agent/rotate.go
- Add missing error messages.
- Fix the order of function calls on errors. (`internalServerError()`～`log.Error()`)
This order is same as other handlers `agent.Health()` and `agent.Clone()`.
=> Add error messages in RotateLog handler

controllers/mysql_clustering.go, controllers/mysqlcluster_controller.go
- Remove duplicate output of MySQLCluster name. The name is set commonly. https://github.com/cybozu-go/moco/blob/54ad80e809100fa01c734dc6edcce7648c1771ac/controllers/mysqlcluster_controller.go#L98
- Output the operation (`CREATE` or `UPDATE`) when reconciling services.
- Lowercase the start of some log messages.
- Output the cluster status when the status could not be updated.
=> Fix controller log additional field

.github/workflows/ci.yaml, e2e/manifests/mysql_cluster.yaml, e2e/manifests/mysql_cluster_external.yaml
Print logs of the following components.
- moco-controller-manager
- MySQLCluster in `e2e-test-external` ns
In this PR, I cannot print the log of MySQLCluster in`e2e-test` ns.
Because the resource is deleted in the k2e test.
https://github.com/cybozu-go/moco/blob/v0.3.1/e2e/gc_test.go
=> Output logs on CI

cmd/entrypoint/cmd/agent.go
Change the log format output from mysql library (`github.com/go-sql-driver/mysql`).
```
[mysql] 2020/12/23 05:53:58 packets.go:122: closing bad idle connection: EOF
```
```
2020-12-23T08:54:18.851335Z mysqlcluster-43f352c5-837f-42ce-8f96-9bc1ceaa3d2b-0 entrypoint error: "[mysql] closing bad idle connection: EOF"
```
=> Set logger to mysql library

e2e/Makefile, test_utils/test_utils.go
The output strings of `test_utils` are difficult to read.
I want to be more readable.
```
cc654874969102f89cc1c1a5534b7a678849ebcbae5f45752389c69a8537d67f ★ What's this? Σ(゜゜)
2021-01-12T05:48:16.875007Z ubuntu-bionic agent.test info: "well: exec" args="[docker run -d --restart=always --network=moco-test-net --name moco-test-mysqld-donor -p 3307:3307 -v /home/m001282/go/src/github.com/cybozu-go/moco/my.cnf:/etc/mysql/conf.d/my.cnf -e MYSQL_ROOT_PASSWORD=test-password mysql:8.0.21 --port=3307 --server-id=1]" command="/usr/bin/docker" response_time=1.09144722 type="exec"
```
```
2021-01-12T05:59:40.722844Z ubuntu-bionic agent.test info: "well: exec" args="[docker run -d --restart=always --network=moco-test-net --name moco-test-mysqld-replica -p 3308:3308 -v …
```
=> test_utils: Make the command output identifiable

.github/workflows/ci.yaml, Makefile, accessor/suite_test.go, agent/suite_test.go, controllers/suite_test.go, initialize/init_test.go, operators/configure_intermediate_primary_test.go, operators/configure_replication_test.go, operators/set_clone_donor_list_test.go, operators/stop_replica_io_thread_test.go, operators/suite_test.go, operators/update_primary_test.go, test_utils/test_utils.go
- Run the small test with MySQL 8.0.18 and 8.0.20
- Remove redundant or unused constants.
- Change the test password: `test-password` -> `testpassword`.
- Because the GitHub Actions will mask the strings `-password <HOGE>` unexpectedly.
- If not change the test password, this command is ...
- `docker run <other param> -e MYSQL_ROOT_PASSWORD=test-password mysql:8.0.18`
- logged as follows. 😱
- `docker run <other param> -e MYSQL_ROOT_PASSWORD=test***`
=> Run small test with MySQL 8.0.18 and 8.0.20

accessor/mysql_accessor_test.go, accessor/mysql_status_test.go, accessor/suite_test.go
Change the accessor test as follows.
- Use a MySQL container launched by `test_utils`.
- Use the appropriate constants for test passwords.
=> Use test_utils in accessor tests

.github/workflows/ci.yaml, .github/workflows/release.yaml, Dockerfile, Makefile, cmd/moco-controller/cmd/root.go, docs/build-mysql.md, e2e/Dockerfile, initialize/Dockerfile, operators/set_labels_test.go
- Update Go to 1.15
- Update Ubuntu to 20.04
`go install` outside `GOPATH` will fail with go 1.15 as follows. So I fixed the relevant part to use `go get`.
```
$ make custom-checker
if ! which custom-checker >/dev/null; then \
cd /tmp; env GOFLAGS= GO111MODULE=on go install github.com/cybozu/neco-containers/golang/analyzer/cmd/custom-checker; \
fi
cannot find module providing package github.com/cybozu/neco-containers/golang/analyzer/cmd/custom-checker: working directory is not part of a module
Makefile:141: recipe for target 'custom-checker' failed
make: *** [custom-checker] Error 1
```
=> Update Go to 1.15 and Ubuntu to 20.04

Makefile, agent/clone_test.go, agent/health_test.go, agent/rotate_test.go, agent/suite_test.go, test_utils/test_utils.go
Change the agent test as follows.
- Use the constants of `test_utils` for test passwords 
- Initialize the primary MySQL as the external donor in the test cases for the clone from external.
- Skip some checks after clone from external.
- In the current test configuration, the initialization after the clone does not succeed. 
- I registered another issue to fix the test. https://github.com/cybozu-go/moco/issues/145
- Some minor changes.
=> Refactor agent test

controllers/mysql_conf.go, docs/build-mysql.md
I tried to use MOCO with the upstream MySQL Images [`mysql:8.0.20`](https://hub.docker.com/_/mysql) and [`mysql/mysql-server:8.0.20`](https://hub.docker.com/r/mysql/mysql-server/).
Then I faced the following error.
```
2021-01-20T14:40:07.396162Z 0 [ERROR] [MY-000067] [Server] unknown variable 'innodb_numa_interleave=ON'.
```
The mysqld binaries in the upstream images may not be built for a NUMA-enabled Linux.
So they cannot recognize the [`innodb_numa_interleave`](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_numa_interleave) option.
It's a bother to change the option when using the upstream based image, so I want to add the `loose_` prefix to it.
And add a note for building MySQL image.
Signed-off-by: Masayuki Ishii masa213f@gmail.com
=> Ready to use upstream MySQL image

e2e/intermediate_primary_test.go
This PR adds the tests:
1. After cloning from the donor, the cluster should continue the asynchronous replication from the donor.
2. When deleting the `replicationSourceSecretName` from the CR, the cluster should stop intermediate primary behavior and should act as a writable cluster.
=> Add more tests for intermediate primary.

config/rbac/mysqlcluster_editor_role.yaml
In general, the `admin` or `editor` role is also set to `deletecollection`.
Please check the privilege of a namespace admin user by the following command.
```
kubectl -n <namespace> --as=user --as-group=<namespace admin group> --as-group=system:authenticated auth can-i --list
```
Without `deletecollection`, the team-management test in neco-apps will not succeed. :(
=> Add deletecollection for admin/edit role

e2e/Makefile
When `e2e/bin/kubectl-moco` already exists, the binary is not built before the e2e test.
To make it easier to do the e2e test in local, I want to fix it.
=> Build kubectl-moco before e2e test

.github/workflows/release.yaml, Makefile
```
$ make release-build
$ file build/*
build/kubectl-moco-darwin-amd64:      Mach-O 64-bit x86_64 executable
build/kubectl-moco-linux-amd64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
build/kubectl-moco-windows-amd64.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```
=> release build target for kubectl-moco

controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go
refs: https://github.com/cybozu-go/moco/issues/172
* Record all passwords in the ControllerSecret.
* RootPasswordSecret and MyCnfSecret are generated from ContollerSecret.
* RootPasswordSecret and MyCnfSecret will be updated in the reconciliation roop.
* If the User updates these secrets, they will be restored in the reconciliation loop.
=> Generate RootPasswordSecret and MyCnfSecret from ControllerSecret

cmd/kubectl-moco/cmd/common.go, cmd/moco-controller/cmd/run.go, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, controllers/suite_test.go, utils.go
Update logic from v0.5.1.
If there is a lack of passwords in a ControllerSecret, fill in missing passwords from a ClusterSecret.
And some refactor.
=> Update controller secret

controllers/mysqlcluster_controller.go
See https://github.com/cybozu-go/moco/issues/193.
This PR reverts an upgrade logic added by https://github.com/cybozu-go/moco/pull/192 .
=> Remove upgrade logic

cmd/moco-controller/cmd/root.go, cmd/moco-controller/cmd/run.go, constants.go, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, controllers/suite_test.go, docs/design.md, docs/moco-controller.md, e2e/Makefile
refs: https://github.com/cybozu-go/moco/issues/174
This pull request depends on the following pull request changes:
https://github.com/cybozu-go/moco-agent/pull/14
Merge the dependent pull requests, release moco-agent, and rerun the E2E tests.
Until then, the test of this pull request will continue to fail.
Stop using moco-conf-gen.
moco-conf-gen process is now included in the moco-agent initialization process.
E2E tests will not work properly without a Container Image with modified moco-agent code.
This is the result of running it on my local machine:
```console
$ pwd # moco-agent repo
/path/to/dir/github.com/cybozu-go/moco-agent
$ git branch
* d-kuro/move-moco-conf-gen
main
$ docker build . -t moco-agent:dev # Create a container image with the modified code
$ kind load docker-image …
```
=> Stop using moco-conf-gen

controllers/mysqlcluster_controller_test.go, docs/design.md, docs/example_mysql_cluster.md, e2e/manifests/mysql_cluster.yaml, e2e/manifests/mysql_cluster_external.yaml
refs: https://github.com/cybozu-go/moco/issues/171
This is one of the pull requests that will be split.
This pull request replaces the existing filebeat container with a fluent-bit container.
After this pull request, I will submit a change to define the default fluent-bit container and allow end users to customize the fluent-bit container.
=> Migrate from filebeat to fluent-bit

controllers/mysqlcluster_controller.go, docs/metrics.md, metrics/deleter.go, metrics/deleter_test.go, metrics/metrics.go, metrics/updater.go, metrics/updater_test.go, runners/suite_test.go
This PR simplifies cluster status metrics.
This also removes the use of `ConditionUnknown` in indexer functions.
Original:
```
moco_controller_cluster_healthy_status{cluster_name="foo", status="true"} 1.0
moco_controller_cluster_healthy_status{cluster_name="foo", status="false"} 0.0
moco_controller_cluster_healthy_status{cluster_name="foo", status="unknown"} 0.0
```
Simplified:
```
moco_controller_cluster_healthy_status{cluster_name="foo"} 1.0
```
=> metrics: simplify status metrics into whether status is true or not.

RELEASE.md, config/manager/manager.yaml
I could not setup this operator with the given configs and I found out that the controller image tag is incorrect.
```
inductor@vm:~$ docker pull ghcr.io/cybozu-go/moco:latest
Error response from daemon: name unknown
inductor@vm:~$ docker pull ghcr.io/cybozu-go/moco:0.7.0
0.7.0: Pulling from cybozu-go/moco
83ee3a23efb7: Pull complete
db98fc6f11f0: Pull complete
f611acd52c6c: Pull complete
686294eef510: Pull complete
e6006b494f03: Pull complete
e7a099f8a1b9: Pull complete
2cc57e483531: Pull complete
Digest: sha256:acacfd013f75a2211506ef805c489d9137518c5e493c3cbcb406847ddfd86026
Status: Downloaded newer image for ghcr.io/cybozu-go/moco:0.7.0
ghcr.io/cybozu-go/moco:0.7.0
```
=> Fix image tag

docs/example_mysql_cluster.md
refs: https://github.com/cybozu-go/moco/issues/171
Added fluent bit config to the documentation, which is generated by default.
=> Add a default generated ConfigMap to the documentation

clustering/agent.go, clustering/mock_test.go, clustering/operations.go, docs/clustering.md, pkg/constants/users.go, pkg/dbop/kill.go, pkg/dbop/kill_test.go, pkg/dbop/operator.go, pkg/dbop/test_util.go, pkg/dbop/types.go
After a switchover, connections in the old primary will probably
not be usable.  To notify clients of the event earlier, MOCO should
kill the existing connections in the old primary.
The implementation does not kill connections from `localhost`
because some system processes such as `event_scheduler` have
such connections.  Also, it does not kill MOCO system users'
connections.
=> Kill connections in the old primary upon a switchover

CHANGELOG.md, controllers/mysql_container.go, controllers/mysqlcluster_controller_test.go, pkg/constants/container.go
to avoid mismatched UID/GID and root execution.
=> controllers: set UID/GID of containers

controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, e2e/manager_patch.yaml
The headless Service should not be configurable.
Fixes #249
Also, the Service reconciler is improved not to overwrite dual-stack related fields.
=> Do not apply Service template to the headless Service

CHANGELOG.md, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, kustomization.yaml, version.go
It failed to update Services when `spec.externalTrafficPolicy` was set to `Local`.
=> controllers: fix a bug in ServiceTemplate reconciliation

CHANGELOG.md, api/v1beta1/mysqlcluster_types.go, clustering/manager_test.go, clustering/operations.go, clustering/process.go, clustering/status.go, clustering/status_test.go, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, controllers/pod_watcher.go, docs/clustering.md, docs/crd_mysqlcluster.md, go.mod, go.sum, kustomization.yaml, version.go
This PR includes multiple bug fixes.
- Failed to clone large data due to a timeout.
- Failed to determine Cloning state correctly.
- Manual switchover might not have taken place immediately.
To fix the first clone bug, `moco-agent` is updated to 0.6.6.
=> Fix cloning bugs

controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, controllers/pod_watcher.go
In order to run reconciliation quickly, the controller needs to watch ConfigMap
referenced by `spec.mysqlConfigMapName` field of MySQLCluster.
=> Watch ConfigMap for customizing my.cnf

backup/key.go
MySQLCluster.Status.Backup.Time is affected by the system time zone when it's retrieved.
CalcKey calculates a key for a storing backup file using the time which is affected by the system time zone, and it leads to the problem that RestoreManager can't find target backup files as expected.
Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>
=> Fix not to be affected by the system time zone

docs/setup.md, docs/usage.md
The link that using relative-path is "404 not found" on GitHub pages.
This PR change URL to the repository from relative-path.
Visitors will is able to found some files.
=> docs: fix a dead link in GitHub pages

backup/backup_test.go, backup/mock_test.go, backup/restore.go, pkg/bkop/operator.go, pkg/bkop/operator_test.go, pkg/bkop/restore.go
When restoring from a backup, we encountered the following error.
```text
mysqlbinlog: Can't create/write to file '/tmp/tmp.HEJ6ct' (OS errno 30 - Read-only file system)
mysqlbinlog: Can't create/write to file '/tmp/tmp.fFkaQp' (OS errno 30 - Read-only file system)
mysqlbinlog: Can't create/write to file '/tmp/tmp.B2u7Xp' (OS errno 30 - Read-only file system)
mysqlbinlog: Can't create/write to file '/tmp/tmp.L82Cpt' (OS errno 30 - Read-only file system)
mysqlbinlog: Can't create/write to file '/tmp/tmp.dFxxlu' (OS errno 30 - Read-only file system)
```
mysqlbinlog requires enough space to be specified as TMPDIR. See the following.
https://dev.mysql.com/doc/refman/8.0/en/mysqlbinlog.html
=> Use workVolume/tmp as TMPDIR for mysqlbinlog

.dockerignore, .github/workflows/release.yaml, .gitignore, .goreleaser.yaml, .krew.yaml, Makefile, docs/install-plugin.md, e2e/Makefile
refs: https://github.com/cybozu-go/moco/issues/313
Release kubectl-moco plugin to krew-index.
* Build the binary to be released using [goreleaser](https://github.com/goreleaser/goreleaser) and archive it as `.tar.gz`
* krew plugins must be packaged as .zip or .tar.gz archives
* https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/#specifying-plugin-download-options
* Use krew-release-bot to update krew-index
* https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/
* Add tar.gz archive to v0.9.5 release
* This will be done manually
* `GORELEASER_CURRENT_TAG=v0.9.5 goreleaser release --skip-publish --skip-announce --skip-validate --rm-dist`
* Send a Pull Request to https://github.com/kubernetes-sigs/krew-index
I've tested it in my own repository that I forked. …
=> Support krew release

pkg/bucket/s3.go, pkg/bucket/s3_test.go
There are several bugs in decidePartSize:
- If objectSize is less than **DefaultPartSize*UploadParts**, DefaultPartSize should be returned.
https://github.com/cybozu-go/moco/blob/c9013554e92fbc97f4d29b0beb67413b16484ab9/pkg/bucket/s3.go#L139
- Parentheses are required for shift operations.
https://github.com/cybozu-go/moco/blob/c9013554e92fbc97f4d29b0beb67413b16484ab9/pkg/bucket/s3.go#L143
Added unittest to decidePartSize.
=> Fixed a bug in decidePartSize calculation

clustering/manager.go, clustering/manager_test.go, controllers/mock_test.go, controllers/mysqlcluster_controller.go, controllers/pod_watcher.go
The context passed as a `Recincle()`'s argument is short-lived.
It is not good for the ClusterManager to depend on the short-lived context.
Regardless of the context, the ClusterManager's goroutines will be stopped here.
https://github.com/cybozu-go/moco/blob/v0.10.9/cmd/moco-controller/cmd/run.go#L86
So we need not add the another deletion function.
=> Stop using Reconcile's context for ClusterManager

backup/backup.go, go.sum
The actual usage should be counted by the number of allocated blocks.
The new result should match with the result of `du` command.
=> backup: calculate disk usage accurately

controllers/mysql_container.go
MOCO refers to the current spec of the StatefulSet when creating the SlowQueryLogContainer.
https://github.com/cybozu-go/moco/blob/abdde66ee673c7232b8c22b7396ed6665dc69ccb/controllers/mysqlcluster_controller.go#L717-L724
When I introduced server-side-apply, we used ExtractStatefulSet to get the applyconfigration, but the first time we server-side-apply, it returns an empty StatefulSetApplyConfigration because the field manager does not exist.
```
"{\"kind\":\"StatefulSet\",\"apiVersion\":\"apps/v1\",\"metadata\":{\"name\":\"moco-fuga\",\"namespace\":\"default\"}}"
```
The resulting spec was nil, which caused a panic.
https://github.com/cybozu-go/moco/blob/abdde66ee673c7232b8c22b7396ed6665dc69ccb/controllers/mysql_container.go#L164-L170
This PullRequest adds a nil check to avoid panic and …
=> Fixed panic when migrating to SSA.

api/v1beta1/conversion.go, api/v1beta1/conversion_test.go
Copy `v1beta1.serviceTemplate` to `v1beta2.primaryServiceTempalate` and `v1beta2.replicaServiceTemplate` when converting from v1beta1 to v1beta2 with MySQLCluster conversion.
=> Copy values to replicaServiceTemplate in conversion webhook

docs/usage.md
=> Update how-to doc to grant PROXY when replicating cluster from outside

controllers/mysqlcluster_controller.go
refs: #306 
Fixed a problem with duplicate keys in the structured log added when server-side-apply was introduced.
example:
```
{"level":"info","ts":1646794776.514839,"logger":"controller.mysqlcluster","msg":"reconciled my.cnf configmap","reconciler group":"moco.cybozu.com","reconciler kind":"MySQLCluster","name":"test","namespace":"test","name":"moco-test.953412cc"}
{"level":"info","ts":1646794776.5734022,"logger":"controller.mysqlcluster","msg":"reconciled configmap for slow logs","reconciler group":"moco.cybozu.com","reconciler kind":"MySQLCluster","name":"test","namespace":"test","name":"moco-slow-log-agent-config-test"}
{"level":"info","ts":1646794776.593614,"logger":"controller.mysqlcluster","msg":"reconciled service account","reconciler group":"moco.cybozu.com","reconciler …
```
=> Fixed duplicate key in structured log

api/v1beta2/mysqlcluster_types.go, api/v1beta2/mysqlcluster_webhook_test.go
refs: #306 
Validate that the container name is non-nil with the validation webhook.
This is a follow-up to the validation that disappeared from the CRD spec when SSA was introduced.
=> Validate that container name is non-nil in validation webhook

controllers/mysql_container.go, controllers/mysqlcluster_controller_test.go
moco v0.11.0 introduced a bug that it did not set `runAsUser` and `runAsGroup` in the user-supplied containers.
In an environment that Pods are restricted to run as a non-root user, this would prevent running mysql pods.
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
=> Add securityContext to the user-specified containers

CHANGELOG.md, kustomization.yaml, version.go
I will write the following description to the release page.
```
Additional Features:
From this release, MOCO automatically sets the resource requests and limits for system containers of MySQL Pods.
This feature will allow you to change the MySQL Pod's QoS by setting the `resources` of the `mysqld` container.
You can overwrite the default resource settings of system containers.
Please read the following document for details.
[Customize default container](./docs/customize-system-container.md)
Breaking Changes:
This release updates the [mysqld_exporter](https://github.com/prometheus/mysqld_exporter) from v0.13.0 to 0.14.0.
Along with this update, some metrics' names have been changed.
Please refer to the following page for details.
https://github.com/prometheus/mysqld_exporter/releases/tag/v0 …
```
=> Bump version to 0.12.0

docs/usage.md
We encountered the following error when executing GRANT statements on the donor while replicating data from the donor with `partial_revokes` disabled to the MySQLCluster by MOCO.
```
Error 'Either some of the authorization IDs in the AS clause are invalid or the current user lacks privileges to execute the statement.' on query. Default database: ''. Query: 'GRANT ALL PRIVILEGES ON *.* TO 'clone-init'@'localhost' WITH GRANT OPTION AS 'skip-grants user'@'skip-grants host' WITH ROLE NONE'
```
[MySQL 8.0 reference manual](https://dev.mysql.com/doc/refman/8.0/en/partial-revokes.html#partial-revokes-replication) says 'In replication scenarios, if partial_revokes is enabled on any host, it must be enabled on all hosts'.
=> Make sure partial_revokes is enabled

docs/designdoc/support_volume_expansion.md
refs: https://github.com/cybozu-go/moco/issues/265
~~Add design documentation for moco-controller to support volume size expansion~~
> **Note**
>
> Rewrote docs to focus on recreating the StatefulSet rather than extending volume
=> Support apply PVC template changes to StatefulSet

.github/workflows/release.yaml
This PR improves Docker build cache using Docker official build action instead of using shell script.
=> Use Docker action

api/v1beta2/backuppolicy_webhook.go, api/v1beta2/mysqlcluster_types.go, api/v1beta2/mysqlcluster_webhook.go, api/v1beta2/mysqlcluster_webhook_test.go, api/v1beta2/webhook_suite_test.go
refs: https://github.com/cybozu-go/moco/issues/265
depends: https://github.com/cybozu-go/moco/pull/417
Currently, does not check to see if the storage class supports volume expansion when the PVC storage size is increased.
validation webhook does not allow the storage size to be reduced, so there is no way for the user to recover from this situation.
Use validation webhooks to see if your storage class supports volume expansion and reject the request if it doesn't.
=> Validate storage class supports volume size expansion

charts/moco/templates/certificate.yaml, charts/moco/templates/issuer.yaml
fix #426
If you specify a name other than `moco` in helm install, `<specified name>-grpc-issuer` will be applied.
However, `moco-grpc-issuer` is referenced in moco-controller.
https://github.com/cybozu-go/moco/blob/ae0c853b7ac893fd6c3bfbb819f2b57d7d5ee97e/controllers/certificate_tmpl.yaml#L16
=> Fix wrong issuer name in helm chart

controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go
Migrate from policyv1beta1.PodDisruptionBudget to policyv1.PodDisruptionBudget.
The former is not available in Kubernetes 1.25.
Fixes #451
Tested with Kubernetes 1.25.
=> Migrate from policyv1beta1.PodDisruptionBudget to policyv1.PodDisruptionBudget

charts/moco/README.md, charts/moco/templates/deployment.yaml, charts/moco/values.yaml
refs: https://github.com/cybozu-go/moco/issues/441
Add four helm values：
* `resources`
* `nodeSelector`
* `affinity`
* `tolerations`
values:
```yaml
resources:
requests:
cpu: 100m
memory: 20Mi
nodeSelector:
foo: bar
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: foo
operator: In
values:
- bar
tolerations:
- key: foo
value: bar
effect: NoSchedule
```
result:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: moco-controller
namespace: default
labels:
app.kubernetes.io/component: moco-controller
helm.sh/chart: moco-0.2.3
app.kubernetes.io/name: moco
app.kubernetes.io/version: "0.12.1"
app.kubernetes.io/managed-by: Helm
spec:
replicas: 2
selector:
matchLabels:
app.kubernetes.io/component: moco-controller …
```
=> Add helm chart values

e2e/Makefile, e2e/backup_test.go, e2e/pvc_test.go, e2e/suite_test.go, e2e/upgrade_test.go
Clean up resources after running E2E tests and extend the test timeout.
These changes the stability of E2E tests.
But, I'm still seeing rare test failures and I will continue to investigate.
=> Delete cluster after E2E

charts/moco/templates/certificate.yaml, config/certmanager/grpc.yaml
Fix https://github.com/cybozu-go/moco/issues/459.
Also see https://github.com/argoproj/argo-cd/issues/6008.
=> Normalize time values in Certificate resource

charts/moco/README.md, charts/moco/templates/deployment.yaml, charts/moco/values.yaml
refs: https://github.com/cybozu-go/moco/issues/462
Add an extraArgs field to the Helm chart that allows specifying moco-controller args.
values.yaml:
```yaml
extraArgs:
- --agent-image=local/moco-agent:0.7.1
```
rendered:
```yaml
apiVersion: apps/v1
kind: Deployment
<snip>
name: moco-controller
args:
- --agent-image=local/moco-agent:0.7.1
ports:
- containerPort: 9443
name: webhook-server
protocol: TCP
- containerPort: 8081
name: health
protocol: TCP
- containerPort: 8080
name: metrics
protocol: TCP
<snip>
```
=> Add extraArgs to helm values.

.github/workflows/helm.yaml
Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>
=> Stop using set-output

charts/moco/Chart.yaml
refs: https://github.com/cybozu-go/moco/issues/463
Current Helm chart does not work with Kubernetes v1.21 or lower by default.
Specify the minimum Kubernetes version.
e.g.
```console
$ helm install moco ./charts/moco/
Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.22.0 which is incompatible with Kubernetes v1.21.12
```
=> Specify minimum Kubernetes version

cmd/kubectl-moco/cmd/completion.go, cmd/kubectl-moco/cmd/credential.go, cmd/kubectl-moco/cmd/mysql.go, cmd/kubectl-moco/cmd/switchover.go
refs: https://github.com/cybozu-go/moco/issues/354
> 📝 
>
> Completion is currently not available via kubectl plugin.
>
> ref: https://github.com/kubernetes/kubernetes/pull/105867
Introduce completion for kubectl-moco.
The `completion` subcommand is now available by default in cobra.
```console
$ kubectl-moco -h
the utility command for MOCO.
Usage:
kubectl-moco [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
<snip>
```
Subcommand completion is currently available.
```console
$ kubectl-moco [tab]
-- completions --
completion  -- Generate the autocompletion script for the specified shell
credential  -- Fetch the credential of a specified user
help        -- Help about any command
mysql       -- Run mysql command in a specified MySQL …
```
=> Introduce completion

cmd/kubectl-moco/cmd/credential.go, cmd/kubectl-moco/cmd/mysql.go
ref: https://github.com/cybozu-go/moco/issues/354, https://github.com/cybozu-go/moco/pull/470
Add a completion for `--mysql-user`(`-u`) option of `kubectl-moco mysql`.
```bash
$ . <(kubectl-moco completion bash)
$ kubectl-moco mysql -u moco- [tab]
-- completions --
moco-admin     moco-readonly  moco-writable
```
=> Completion mysql-user option in kubectl-moco mysql

.github/workflows/ci-e2e.yaml, .github/workflows/ci.yaml, .github/workflows/dbtest.yaml, .github/workflows/e2e.yaml, .github/workflows/weekly.yaml, DEVELOP.md
There are many versions of MySQL supported by MOCO.
> MySQL: 8.0.18, 8.0.25, 8.0.26, 8.0.27, 8.0.28, 8.0.30
Since the matrix test will continue to grow if this is not done, the following policy is established.
* Determine the MySQL version of the LTS
* This is the version that Cybozu uses internally
* In addition to the LTS version, CI will run the latest and one of the previous versions
* Matrix tests for all supported MySQL versions are run on a weekly basis
=> Use reusing workflow

controllers/mysql_container.go, controllers/mysqlcluster_controller_test.go, examples/custom-probe.yaml
refs: https://github.com/cybozu-go/moco/issues/361
Allows the user to configure mysql container probe.
=> Uses a probe defined by the user

docs/usage.md
I tried to setup a MySQL cluster following the instruction below, but `INSTALL PLUGIN` command failed.
https://cybozu-go.github.io/moco/usage.html#creating-a-cluster-that-replicates-data-from-an-external-mysqld
```
mysql> INSTALL PLUGIN clone SONAME mysql_clone.so;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysql_clone.so' at line 1
```
It seems that `INSTALL PLUGIN clone SONAME 'mysql_clone.so';` is correct according to the official document.
https://dev.mysql.com/doc/refman/8.0/en/clone-plugin-installation.html
=> Fix INSTALL PLUGIN command in the usage document

charts/moco/CHANGELOG.md, charts/moco/Chart.yaml
#483 
Relax the `kubeVersion` constraints in Chart.yaml. The `kubeVersion` will be updated when there is an obviously uninstallable version. 
=> Relax the kubeVersion constraints in Chart.yaml

docs/designdoc/object_storage_type.md
refs: https://github.com/cybozu-go/moco/issues/427
Propose API enhancements to allow GCS and other non-S3 compatible object storage to be used from MOCO
=> Added proposal to support non-S3 compatible object storage

clustering/process.go, docs/metrics.md, pkg/metrics/metrics.go
Add metrics to measure the processing time of cluster-manager goroutines.
It may be helpful with performance tuning.
| Name                                | Type    |
|-------------------------------------|--------|
| `moco_cluster_processing_time_seconds` | histogram |
With this change, the moco-controller will expose the following metrics.
```
$ curl -sS localhost:8080/metrics | grep processing_time
moco_cluster_processing_time_seconds_bucket{name="cluster1",namespace="foo",le="0.1"} 7
moco_cluster_processing_time_seconds_bucket{name="cluster1",namespace="foo",le="0.25"} 19
moco_cluster_processing_time_seconds_bucket{name="cluster1",namespace="foo",le="0.5"} 19
moco_cluster_processing_time_seconds_bucket{name="cluster1",namespace="foo",le="0.75"} 19 …
```
=> Add metrics to measure processing time

e2e/failover_test.go, e2e/testdata/failover.yaml, pkg/dbop/gtid.go
refs: https://github.com/cybozu-go/moco/issues/370
Use Executed_Gtid_Set and Retrieved_Gtid_Set when determining the primary.
Previously, only Retrieved_Gtid_Set was used to select the primary.
However, there are cases where Retrieved_Gtid_Set is empty immediately after replication starts if there are no new transactions.
```console
$ kubectl-moco mysql test --index 2 -- -e "SHOW REPLICA STATUS\G"
*************************** 1. row ***************************
Replica_IO_State: Waiting for source to send event
...
Retrieved_Gtid_Set:
Executed_Gtid_Set: 09a2bf6a-960c-11ec-bf89-9ee9543e8238:1,
09c0848a-960c-11ec-90e9-0a55db88221e:1-4
...
```
Therefore, change to also use ExecutedGtidSet for finding primary.
```go
// There are cases where Retrieved_Gtid_Set is empty,
// such as when there is …
```
=> Use ExecutedGtidSet and RetrievedGtidSet when determining the primary

cmd/moco-controller/cmd/root.go, cmd/moco-controller/cmd/run.go, docs/moco-controller.md, pkg/pprof/pprof.go
Add pprof server to moco-controller.
The pprof server will start only when `--pprof-addr` option is set.
> **Note**
> We can remove the `pprof.Handler` added in this PR after merging the following PR into the controller runtime.
> https://github.com/kubernetes-sigs/controller-runtime/pull/1943
Usage: View the trace data
1. Deploy the moco-controller with `--pprof-addr=:9090` option.
2. Get trace data and run the trace viewer.
```bash
$ kubectl port-forward -n moco-system POD_NAME  9090:9090 &
$ curl -s http://localhost:9090/debug/pprof/trace?seconds=10 > trace.out
$ go tool trace -http="localhost:9091" trace.out 
```
3. Open `http://localhost:9091` with a Web brower.
=> Add pprof server to moco-controller

clustering/manager_test.go, clustering/mock_test.go, clustering/status.go, pkg/dbop/gtid.go, pkg/dbop/nop.go, pkg/dbop/operator.go, pkg/dbop/types.go
refs: https://github.com/cybozu-go/moco/issues/419
When the primary MySQL load is high, in the rare case, it will delay the execution of transactions in the primary, and the `gtid_executed` of replicas precedes the primary.
In this case, the moco-controller recognizes preceding replicas as errant replicas and purges them from a MySQLCluster.
We have faced this situation twice, and in both cases, the moco-controller purged all replicas, and the MySQLCluster became unavailable.
This PR fixes the detection logic for errant transactions to prevent cluster collapse as described above.
We allow replicas to precede the primary only one event.
=> Ignore primary's event when detecting errant replicas

clustering/log.go, clustering/manager.go, clustering/manager_test.go, clustering/operations.go, clustering/process.go, clustering/status.go, cmd/moco-controller/cmd/run.go, controllers/mock_test.go, controllers/mysqlcluster_controller.go, controllers/pod_watcher.go
This PR fixes the cluster-manager's log.
- Generate an unique string for each cluster-manager's operation. And add it to the log events as `operationId` filed.
- Output log events on start and end for cluster-manager's operation.
- Record the cause of cluster-manager's operation as `origin` field.
After
```json
{"level":"info","ts":"2023-02-08T10:55:39Z","msg":"detected mysql pod deletion","controller":"pod","controllerGroup":"","controllerKind":"Pod","Pod":{"name":"moco-single-0","namespace":"foo"},"namespace":"foo","name":"moco-single-0","reconcileID":"dd11da41-a28f-4b3f-9bde-a98bf9cebbbd","name":"moco-single-0"}
{"level":"info","ts":"2023-02-08T10:55:39Z","logger":"cluster-manager.foo/single","msg":"start operation","operationId":"op-6tklf","origin":"dd11da41-a28f-4b3f-9bde-a98bf9cebbbd …
```
=> Add id to cluster manager's log

version.go
Update the default fluent-bit version to v2.0.9 from v1.9.7.
The major version of fluent-bit has gone up, but there are no significant changes to the plugins which MOCO uses.
https://github.com/fluent/fluent-bit/releases/tag/v2.0.0
> **Note**
> MOCO uses the tail input plugin and the file output plugin.
> https://github.com/cybozu-go/moco/blob/v0.14.1/controllers/mysqlcluster_controller.go#L523-L536
=> Update fluent-bit v2.0.9

CHANGELOG.md, kustomization.yaml, version.go
I don't list https://github.com/cybozu-go/moco/pull/493 in the change log, because it is not yet implemented.
=> Bump version to 0.15.0

e2e/Makefile, e2e/backup_test.go, e2e/failover_test.go, e2e/failure_test.go, e2e/lifecycle_test.go, e2e/pvc_test.go, e2e/replication_test.go, e2e/upgrade_test.go
The machine resources available to GitHub Actions runners are limited,
and it has been confirmed that instability due to issues such as OOM can occur when multiple MySQL Cluster pods created for multiple E2E scenarios exist at the same time.
In this PR, we will wait for the pod to disappear during E2E cleanup to avoid exceeding the expected resource usage of the runner.
=> Wait until all Pods are deleted in E2E

pkg/dbop/kill_test.go
This PR fixes a flaky test of killing process.
There is a time lag until processes are actually deleted after the `KILL CONNECTION` command.
So I use `Eventually` and waite for the deletion.
=> Fix flaky test

controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/usage.md
* https://github.com/cybozu-go/moco/pull/471
Related to the above pull request, a change will be made to set preferredDuringSchedulingIgnoredDuringExecution as the default configuration in the MySQL Cluster Pod.
=> Add podAntiAffinity to MySQL Cluster StatefulSet.

.github/workflows/release.yaml
The moco-backup image cannot be built for linux/arm64.
So I will stop releasing ARM64 images.
When releasing MOCO v0.16.0, I failed to build the moco-backup image.
I tried to fix it but could not immediately because the mysql-shell for linux/arm64 is not provided on the official site.
https://github.com/cybozu-go/moco/actions/runs/4627054740/jobs/8184735343
```
> [linux/arm64 stage-3 6/6] RUN apt-get update   && apt-get install -y --no-install-recommends libjemalloc2 zstd python3 libpython3.8 s3cmd   && rm -rf /var/lib/apt/lists/*   && curl -o /tmp/mysqlsh.deb -fsL https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell_8.0.30-1ubuntu20.04_amd64.deb   && dpkg -i /tmp/mysqlsh.deb   && rm -f /tmp/mysqlsh.deb:
#25 63.01 Setting up python3-six (1.14.0-2) ...
#25 65.34 Setting up …
```
=> Stop releasing ARM64 image

pkg/mycnf/generator.go, pkg/mycnf/testdata/bufsize.cnf, pkg/mycnf/testdata/loose.cnf, pkg/mycnf/testdata/nil.cnf, pkg/mycnf/testdata/normalize.cnf, pkg/mycnf/testdata/opaque.cnf
refs https://github.com/cybozu-go/moco/issues/530
This PR disables `innodb_undo_log_truncate` by default.
Because the `undo log truncate` always fails on replica instances which are `set super_read_only = 1`.
https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_undo_log_truncate
https://bugs.mysql.com/bug.php?id=104573
=> Disable innodb_undo_log_truncate

api/v1beta1/mysqlcluster_types.go, api/v1beta2/mysqlcluster_types.go, docs/crd_mysqlcluster_v1beta1.md, docs/crd_mysqlcluster_v1beta2.md
fix: https://github.com/cybozu-go/moco/issues/524
=> MySQLClusterSpec.BackupPolicyName should be annotated omitempty

e2e/lifecycle_test.go, e2e/testdata/backup.yaml, e2e/testdata/backup_gcs.yaml, e2e/testdata/donor.yaml, e2e/testdata/failover.yaml, e2e/testdata/failure.yaml, e2e/testdata/pvc_test.yaml, e2e/testdata/pvc_test_changed.yaml, e2e/testdata/replication.yaml, e2e/testdata/restore.yaml, e2e/testdata/restore_gcs.yaml, e2e/testdata/single.yaml, e2e/testdata/upgrade.yaml
With this PR https://github.com/cybozu-go/moco/pull/510, now we delete used MySQLClusters at the end of each test case.
Thus, we can run tests with default resource requests.
In addition, I will add a test to confirm that a MySQLCluster is configurable for guarranteed QoS.
=> Remove resoruces overwrite in e2e

charts/moco/Chart.yaml
AWS EKS version syntax is 1.27.3-eks-a5565ad which leads to errors like :
Error: chart requires kubeVersion: >= 1.22.0 which is incompatible with Kubernetes v1.27.3-eks-a5565ad
This PR set version compatibility as EKS friendly.
=> Set kubeVersion compatible with EKS

docs/designdoc/support_apply_pvc_template_changes.md, docs/designdoc/support_reduce_volume_size.md
refs: https://github.com/cybozu-go/moco/issues/537
=> Add proposal to reduce volume size

containers/fluent-bit/README.md, containers/mysqld_exporter/README.md
This PR fixes the wrong links.
I had made a wrong point :(
https://github.com/cybozu-go/moco/pull/528#discussion_r1227688584
=> Fix wrong link

e2e/Makefile, go.mod, go.sum
=> incorporate moco-agent v0.10.0

version.go
Update `version.go` to use the containers built in #553
=> Updating mysqld_exporter and fluent-bit images used in moco

clustering/status.go, e2e/suite_test.go
This PR fixes the retry message when gathering mysqld status.
The current error message is confusing whether it's in retrying or MySQL is finally treated as Not-Ready.
=> Fix retry message when gathering mysqld status

controllers/pod_watcher.go
This PR fixes the log message when `kubectl moco switchover` is executed.
The current message is confusing because the controller outputs `detected mysql pod deletion` even though the pod has not been deleted.
=> Fix log message when demote annotation is added

backup/restore.go, backup/restore_test.go
A bug in RestoreManager.FindNearestDump caused the problem.
Fixes #563.
=> backup: PITR did not work sometimes

docs/designdoc/clustering_stop.md
refs: https://github.com/cybozu-go/moco/issues/564
=> Add proposal for Pause and Resume of MySQL Cluster Clustering

README.md
MOCO supports (tests) the LTS releases of MySQL 8.
We will not test the Innovation releases in our CI.
=> Revised MySQL Support Policy

docs/designdoc/clustering_stop.md
refs: https://github.com/cybozu-go/moco/issues/564
=> Update proposal to allow individual stopping of clustering and reconciliation

clustering/manager_test.go
This PR makes the following changes to the envtest.
1. Use Gomega matcher in `Eventually` block.
It's just a refactoring.
2. Check the pods' metadata in `Eventually` or `Consistently` blocks.
The pods' metadata are updated asynchronously with MySQLCluster's `.status`.
With the current implementation, pods's metadata are checked just once using `Expect`.
Therefore, if there is a delay in updating the pods' metadata, the test may fail. 
3. Add more checks for pods's labels.
Preparation for https://github.com/cybozu-go/moco/pull/561
=> Use Gomega matcher in Eventually and check pods' labels

clustering/mock_test.go, clustering/operations.go, pkg/dbop/gtid.go, pkg/dbop/gtid_test.go, pkg/dbop/nop.go, pkg/dbop/operator.go
This PR removes the copy code of FindTopRunner.
Currently, FindTopRunner is defined twice, for mock and for actual mysql.
And the following PR made a difference.
https://github.com/cybozu-go/moco/pull/474
=> Remove copy code of FindTopRunner

controllers/mysqlcluster_controller.go
This pull request eliminates code duplication related to server side apply in the Reconciler. By introducing a new apply() function, we have been able to eliminate duplication in 13 places.
=> Deduplicate SSA related code

api/v1beta1/backuppolicy_types.go, api/v1beta1/mysqlcluster_types.go, api/v1beta2/backuppolicy_types.go, api/v1beta2/mysqlcluster_types.go, charts/moco/templates/generated/crds/moco_crds.yaml, config/crd/bases/moco.cybozu.com_backuppolicies.yaml, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_backuppolicies.moco.cybozu.com.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_mysqlclusters.moco.cybozu.com.yaml
We are going to deprecate v1beta1, so need to change the
storage version first.
Part of #545
=> api: change the storage version to v1beta2

clustering/manager_test.go, clustering/mock_test.go, clustering/operations.go
This PR fixes failover failure.
When the network of a node that the Primary MySQL Pod runs on is unavailable, the MOCO executes a failover.
However, if the network of the node is restored during the failover, 
failover gets stuck, and MySQLCluster will be unavailable for a long time.
=> Kill old connections when demoting primary

api/v1beta1/backuppolicy_types.go, api/v1beta1/mysqlcluster_types.go, charts/moco/templates/generated/crds/moco_crds.yaml, config/crd/bases/moco.cybozu.com_backuppolicies.yaml, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_backuppolicies.moco.cybozu.com.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_mysqlclusters.moco.cybozu.com.yaml
add deprecatedversion marker.
Part of https://github.com/cybozu-go/moco/issues/545
=> api: add deprecatedversion marker

CHANGELOG.md, api/v1beta1/job_types.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/job_types.go, charts/moco/templates/generated/crds/moco_crds.yaml, cmd/moco-backup/cmd/root.go, config/crd/bases/moco.cybozu.com_backuppolicies.yaml, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_backuppolicies.moco.cybozu.com.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_mysqlclusters.moco.cybozu.com.yaml, controllers/mysqlcluster_controller.go, docs/crd_backuppolicy_v1beta1.md, docs/crd_backuppolicy_v1beta2.md, docs/crd_mysqlcluster_v1beta1.md, docs/crd_mysqlcluster_v1beta2.md, docs/moco-backup.md, e2e/Makefile, e2e/backup_test.go, e2e/backup_tls_test.go, e2e/minio-tls.yaml, e2e/minio.yaml, e2e/run_test.go, e2e/testdata/backup.yaml, e2e/testdata/backup_tls.yaml, e2e/testdata/makebucket.yaml, e2e/testdata/makebucket_tls.yaml, e2e/testdata/restore.yaml, e2e/testdata/restore_tls.yaml
- Add `ca-cert` flag to moco-backup
- Add `caCert` field to BackupPolicy
- Enable minio tls used for testing
- Add test using minio with TLS
- refactoring: Use Gomega matcher in Eventually on backup_test
=> Add tls settings for BackupPolicy

CHANGELOG.md, kustomization.yaml, version.go
With this release, the storage version of CRD has been changed from `v1beta1` to `v1beta2`. [#586](https://github.com/cybozu-go/moco/pull/586)
In addition, `v1beta1` has been deprecated and will be removed in the next version. [#592](https://github.com/cybozu-go/moco/pull/592)
=> Bump version to 0.18.0

CHANGELOG.md, kustomization.yaml, version.go
The release workflow for 0.18.0 failed due to an error, and will be corrected and re-released as 0.18.1.
=> Bump version to 0.18.1

pkg/bkop/backup.go, pkg/bkop/restore.go
If `--passwords-from-stdin` is used, password prompt will be output and it may be handled as a log line without LF. The behavior is problematic because the log line occupies the partial line buffer in logging agent like promtail and will never be flushed naturally.
The command arguments are not visible from outside of the Pod. So this modification is not insecure.
=> pass password via command arguments on backup

api/v1beta2/mysqlcluster_types.go, charts/moco/templates/generated/crds/moco_crds.yaml, clustering/manager.go, clustering/process.go, cmd/kubectl-moco/cmd/start.go, cmd/kubectl-moco/cmd/stop.go, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_mysqlclusters.moco.cybozu.com.yaml, controllers/mock_test.go, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/metrics.md, docs/usage.md, e2e/Makefile, e2e/stop_test.go, e2e/testdata/stop.yaml, e2e/testdata/stop_changed.yaml, pkg/constants/meta.go, pkg/metrics/metrics.go
refs: 
https://github.com/cybozu-go/moco/issues/572
https://github.com/cybozu-go/moco/issues/564
Add the enhancement to stop clustering and reconciling MySQLCluster based on the following design document.
https://github.com/cybozu-go/moco/blob/main/docs/designdoc/clustering_stop.md
=> Stop reconciliation and clustering

cmd/moco-controller/cmd/root.go, cmd/moco-controller/cmd/run.go, controllers/mysqlcluster_controller.go, controllers/pvc.go, controllers/pvc_test.go, docs/change-pvc-template.md
refs: https://github.com/cybozu-go/moco/issues/558
https://github.com/cybozu-go/moco/issues/558#issuecomment-1690940455
Update the value if the label and annotation of the PVC is identical to the label and annotation key of the volumeClaimTemplate based on the above comment specification.
=> Sync PVC labels and annotations

.github/workflows/ci-e2e.yaml, .github/workflows/dbtest.yaml, .github/workflows/e2e.yaml, .github/workflows/handle-pr-comments.yaml, DEVELOP.md
- "OWNER", "COLLABORATOR", and "CONTRIBUTOR" comment `/test` in the PR, the e2e test is executed.
- In converting `ci-e2e` to `workflow_dispatch`, status checks are now updated manually in workflow.
- ~using `myrotvorets/set-commit-status-action`~
- Added process to ci-e2e to retrieve branches to be tested.
- With `on.pull_request`, the post-merge branch was used for testing without the trigger being aware of it, but with `on.workflow_dispath`, the `github.ref` is the branch that was executed and the post-merge branch is not used.
- The `.on.issue_comment` workflow is not executed until merged into the main branch, so commenting `/test` on this PR will not execute the e2e test.
=> Convert e2e to workflow_dispatch

.github/workflows/ci-e2e.yaml, .github/workflows/handle-pr-comments.yaml
I thought `gh pr view --json number -q .number` was failing in the main branch,
but the whole test was failing, so I fixed it.
Change the authority to skip the comment `/test`.
https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
=> Fix ci-e2e on main branch

docs/usage.md, e2e/backup_with_env_test.go, e2e/testdata/backup_with_env.yaml, e2e/testdata/restore_with_env.yaml
Currently, there is no way to set the `ObjectBucketName` in ConfigMap or Secrets. This can be accomplished by using envFrom without adding new functionality.
So we have added docs and some test cases in this PR.
Signed-off-by: yamatcha <soju-yamashita@cybozu.co.jp>
=> Support backup and restore with ObjectBucketName set in environment variables

docs/change-pvc-template.md
* https://github.com/cybozu-go/moco/pull/613
Corrected explanation of synchronization of labels and annotations that was not updated in Pull Reqeusts above.
=> Fix docs regarding sync of labels and annotations

.github/workflows/handle-pr-comments.yaml
If the workflow for the /test comment is unintentionally skipped, it is difficult to resolve the issue.
Added a step to show why /test comments were skipped.
=> Add step to show why e2e test is not triggered successfully

api/v1beta2/mysqlcluster_types.go, charts/moco/templates/generated/crds/moco_crds.yaml, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_mysqlclusters.moco.cybozu.com.yaml, controllers/mysql_container.go, controllers/mysqlcluster_controller_test.go, docs/crd_mysqlcluster_v1beta2.md, pkg/constants/constants.go
When running with istio enabled the communication between the agent and mysqld fails. To overcome this the admin interface for mysqld should be bound to `localhost` and the agent should communicate on `localhost` as well, rather than using pod name.
[More context here](https://github.com/cybozu-go/moco/pull/658#issuecomment-2012142633)
Corresponding moco-agent PR here: https://github.com/cybozu-go/moco-agent/pull/92
I also noticed that `max-delay` and `log-rotation-schedule` are being split across multiple lines when passed to the agent sidecar, which seemes unintentional.
=>  Option to to use localhost instead of pod name

Makefile, charts/moco/templates/generated/crds/moco_crds.yaml, charts/moco/values.yaml, config/kustomize-to-helm/overlays/crds/kustomization.yaml
I was trying to deal with #682 to move CRDs from `templates/generated/crds/` to `crds/`, but I found out that one CRD has configured conversion webhook and certificate, which are deployment/environment specific:
https://github.com/cybozu-go/moco/blob/a683b05a3cc2692114743f4c3f71ab660d22109c/charts/moco/templates/generated/crds/moco_crds.yaml#L2073-L2074 Hmm... So I came with a different approach, which is used also in some other projects: leave it part of templates, but make it conditional and prevent Helm to remove it.
Similar approach can be seen in cert-manager or Rook, e.g.:
- https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/resources.yaml#L1
- https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/resources.yaml#L8
Changes:
- new …
=> Helm chart CRDs optional and not deleted on uninstall

charts/moco/CHANGELOG.md, charts/moco/README.md
part of https://github.com/cybozu-go/moco/issues/682
This PR adds a caution for updating the chart.
When user updates MOCO Chart from chart v0.10.x or lower with `--set crds.enabled=false`, CRDs will be removed.
1. Install chart v0.10.2
```console
$ git checkout chart-v0.10.2
$ helm install --create-namespace --namespace moco-system moco charts/moco/
NAME: moco
LAST DEPLOYED: Tue Jun  4 16:39:42 2024
NAMESPACE: moco-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
$ kubectl get crd
NAME                                  CREATED AT
backuppolicies.moco.cybozu.com        2024-06-04T07:39:43Z
certificaterequests.cert-manager.io   2024-06-04T07:37:31Z
certificates.cert-manager.io          2024-06-04T07:37:31Z
challenges.acme.cert-manager.io       2024-06-04T07:37:32Z …
```
=> Add caution for updating chart to v0.11.x

.github/workflows/release.yaml, Dockerfile
Related issue #490
Enables linux/arm64 build platform back for controller/backup images and installs the MySQL Shell from tar archive (which **is** available also for ARM), instead of Ubuntu package (which is available **only** for x86-64). I did basic testing of controller/backup and all looked working on both platforms.
=> Build and release Moco controller/backup images for arm64

charts/moco/README.md, charts/moco/templates/deployment.yaml, charts/moco/values.yaml
Covers configurable
- replica count
- image pull policy
- reference to secrets for image pulling from authenticated container registry
Nothing really super important, but it might come handy to have these options easily configurable.
=> Add basic Helm chart values

api/v1beta2/mysqlcluster_types.go, backup/backup.go, charts/moco/templates/generated/crds/moco_crds.yaml, clustering/process.go, clustering/status.go, cmd/kubectl-moco/cmd/switchover.go, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_mysqlclusters.moco.cybozu.com.yaml, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/crd_mysqlcluster_v1beta2.md, e2e/backup_with_env_test.go, e2e/failover_test.go, e2e/failure_test.go, e2e/lifecycle_test.go, e2e/offline_test.go, e2e/pvc_test.go, e2e/replication_test.go, e2e/run_test.go, e2e/stop_test.go, e2e/testdata/offline_test.yaml, e2e/testdata/offline_test_changed.yaml, e2e/upgrade_test.go
Fixes: https://github.com/cybozu-go/moco/issues/659
Hi! I'm looking for guidance on the general approach here.
Overall this functions fine in my in-cluster testing but I'm only using a small sub-set of functionality.
=> Allow setting a cluster offline

pkg/dbop/kill_test.go
https://github.com/cybozu-go/moco/issues/710
=> issue-710: add test for kill_test.go

controllers/mysqlcluster_controller_test.go
Thanks to [ginkgolinter](https://github.com/nunnatsa/ginkgolinter), the following mistake was found.
```text
controllers/mysqlcluster_controller_test.go:236:3: ginkgo-linter: "Eventually": missing assertion method. Expected "Should()" or "ShouldNot()" (ginkgolinter)
Eventually(func() error {
^
```
=> Add missing assertion method

controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/reconcile.md
ref https://github.com/cybozu-go/moco/issues/721
This PR allows customization of primary/replica service ports.
With this update, users can specify their port to the `nodePort`.
However, the same as always, for the `mysql` and `mysqlx` ports, MOCO overwrites the fixed value to the `port`, `protocol` and `targetPort` fields.
=> Allows customization of service ports

docs/usage.md
This PR adds a procedure to set MySQL clusters to read-only.
If an user simply sets the "(super_)read_only" variable, MOCO will remove it in the clustering process.
And it can lead to accidents.
Therefore, I specify the procedure to stop clustering and make the cluster read-only.
=> Add procedure to set cluster to read-only

api/v1beta2/mysqlcluster_types.go, api/v1beta2/mysqlcluster_webhook_test.go, backup/backup_test.go, backup/integration_test.go, backup/mock_test.go, backup/restore.go, charts/moco/templates/generated/crds/moco_crds.yaml, cmd/moco-backup/cmd/restore.go, config/crd/bases/moco.cybozu.com_mysqlclusters.yaml, config/crd/tests/apiextensions.k8s.io_v1_customresourcedefinition_mysqlclusters.moco.cybozu.com.yaml, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/crd_mysqlcluster_v1beta2.md, e2e/backup_test.go, e2e/testdata/restore1.yaml, e2e/testdata/restore2.yaml, pkg/bkop/operator.go, pkg/bkop/operator_test.go, pkg/bkop/restore.go
https://github.com/cybozu-go/moco/issues/725
=> Load only the named schema from the dump files

docs/designdoc/safe_statefulset_rolling_update.md
refs: https://github.com/cybozu-go/moco/issues/622
=> Add designdoc for Safe Rolling Update of StatefulSet

cmd/kubectl-moco/cmd/start.go, cmd/kubectl-moco/cmd/stop.go
=> Add a line break to kubectl-moco start/stop command's message

cmd/moco-controller/cmd/root.go, cmd/moco-controller/cmd/run.go, controllers/mysqlcluster_controller.go, controllers/mysqlcluster_controller_test.go, docs/moco-controller.md
refs: https://github.com/cybozu-go/moco/issues/540
Introduce my.cnf configmap generation management.
This prevents the configmap being used from being deleted.
=> Add mysql-configmap-history-limit flags

clustering/operations.go
https://github.com/cybozu-go/moco/issues/745
=> issue-745: Set timeoutSeconds to 50sec

charts/moco/templates/_helpers.tpl, charts/moco/templates/generated/generated.yaml, config/kustomize-to-helm/overlays/templates/kustomization.yaml
https://github.com/cybozu-go/moco/issues/759
=> issue-759: Select the appropriate apiVersion

docs/known_issues.md
https://github.com/cybozu-go/moco/issues/322
=> issue-322: update known issues

e2e/Makefile, e2e/backup_with_env_test.go, e2e/prevent_delete_test.go, e2e/suite_test.go, e2e/testdata/backup_with_env.yaml, e2e/testdata/makebucket_with_env.yaml, e2e/testdata/restore_with_env.yaml
Currently, e2e tests are executed sequentially, so the more tests there are, the longer the test execution time will be.
This PR makes tests run in parallel.
=> Run e2e test in parallel

go.mod, go.sum
In aws-sdk-go-v2 service/s3 v1.73.0, the change of integrity check behavior included.
https://github.com/aws/aws-sdk-go-v2/discussions/2960
=> Downgrade aws-sdk-go-v2/service/s3

.github/actions/dbtest/action.yaml, .github/actions/e2e/action.yaml, .github/actions/setup-aqua/action.yaml, .github/actions/upgrade/action.yaml, .github/workflows/ci.yaml, .github/workflows/mdbook.yaml, DEVELOP.md, Makefile, aqua-checksums.json, aqua.yaml, e2e/Makefile
This pull request introduces the use of Aqua, a declarative CLI version manager, to streamline the management of development tools across the project. It replaces manual tool installation scripts with Aqua's configuration, updates documentation, and modifies Makefiles to integrate Aqua into the development workflow.
=> Manage CLI tools by aquaproj/aqua

clustering/manager_test.go, clustering/operations.go
This commit fixes an issue where errant transactions could propagate through clusters due to premature role=replica labeling of dead pods.
When a MySQL pod with errant transactions dies, the current implementation adds the role=replica label to pods before checking for errant transactions. This creates a window where other clusters can mistakenly replicate from a pod with errant transactions.
Fix #801
=> Dead pods should not be labeled with role=replica

CHANGELOG.md, controllers/mysql_container.go, controllers/mysqlcluster_controller_test.go
See https://github.com/cybozu-go/moco/issues/834
=> fix: only set runAsUser and runAsGroup if they are not specified
